# Generated by Django 2.2.28 on 2026-03-15 19:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import market.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, validators=[market.models.validate_not_prohibited])),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('FURNITURE', 'Furniture'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('STATIONERY', 'Stationery'), ('BOOKS', 'Books'), ('SPORTS', 'Sports'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], db_index=True, default='AVAILABLE', max_length=16)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_listed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('TOPUP', 'Topup')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='market.Item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('photoID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=512)),
                ('caption', models.CharField(blank=True, max_length=256)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='market.Item')),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'status'], name='market_item_categor_d7925e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['listed_at'], name='market_item_listed__d7fa30_idx'),
        ),
    ]
